version: "3"
services:
  db:
    image: postgres:12
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'demo'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
